### ISSUE TITLE
Application not loading in production mode

### ISSUE THREAD

**Issue by VivekKhandre** [CharlBest/nean-stack-starter#77]
After setting up correct process.env. Start application in production mode. Expected to display home page however it is not loading. Same issue is present when visited https://nean.io/.

**Comment by CharlBest** [comment]
Hi @VivekKhandre thank you for taking a look at the project. I appreciate it. 

Do you have any console errors when you visit https://nean.io
In development (local on you computer) when you run launch prod the projects port is 3000. 
all routes with /api are the API and the rest which is just suppose to be index.html and assets are the client application. This is being caught but the * route handler.

Please let me know if I can help you are more? I will reply faster now that I know of the problem.
